micronaut:
  application:
    name: customer
datasources:
  default:
    url: jdbc:mysql://localhost:3306/V1?createDatabaseIfNotExist=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa.properties.hibernate.ddl.auto: update

netty:
  default:
    allocator:
      max-order: 3
